[package]
name = "crystals_kyber"
version = "0.1.0"
authors = ["Simon Pohmann <simon@pohmann.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.8.2"
